# Generated by Django 4.0.3 on 2023-08-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hat',
            options={'ordering': ('style_name', 'fabric', 'color', 'image_url', 'location')},
        ),
    ]
